### ISSUE TITLE
The "Mark as Read" button appears twice

### ISSUE THREAD

**Issue by ericxuo** [nneul/tt-rss-one-click-catchup#1]
Hi,

The plugin works fine. The only problem I've found is that the button appears twice, on the left and on the right on the main page.
Is it possible to remove the one on the right ?

![ksnip_20220626-192933](https://user-images.githubusercontent.com/9089499/175826705-c808cf34-1711-46fd-9f7e-5ff6a84d91e7.png)

("Marquer comme lu" stands for "Mark as Read").

Regards.

Xuo.

**Comment by nneul** [comment]
That was actually intentional, but I'll see if I can add in a preference item for it to set that.

**Comment by nneul** [comment]
In the mean time, just comment out either of the add_hook calls. MAIN_TOOLBAR is the left one.

**Comment by nneul** [comment]
Try v0.2 - there should be a new preference tab for the plugin with ability to hide either button.

**Comment by nneul** [comment]
![image](https://user-images.githubusercontent.com/828492/175831004-fe0ecf6f-471b-4176-bc42-5b3ad418f82c.png)

**Comment by nneul** [comment]
Further improvements in v0.3 to optionally allow hiding the existing Mark as read drop down menu.

**Comment by ericxuo** [comment]
Hi,

Everything works fine. Version 0.3 as well. Thank you very much.

Regards.

Xuo.
