### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by fbuescher** [nneul/tt-rss-one-click-catchup#5]
Hi,

would you like to consider a setting that actually *replaces* the mark-as-read-dropdown completely?

I do not need to mark "older than 2 weeks" and so on, it's just a waste of space.

regards,
Friedhelm

**Comment by nneul** [comment]
See v0.3 and you can do exactly that.

**Comment by nneul** [comment]
To get as close to what you're looking for:  Check Hide left, Uncheck Hide Right, Check Hide dropdown in plugin preferences

**Comment by fbuescher** [comment]
excellent!

Thank you!
